### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by martadd** [WFRT/verif#98]
Kindly help me with this error

[martin@localhost examples]$ verif raw.txt k.txt -m mae
Traceback (most recent call last):
  File "/home/martin/anaconda3/bin/verif", line 11, in <module>
    load_entry_point('verif==1.0.0', 'console_scripts', 'verif')()
  File "/home/martin/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/martin/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/home/martin/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/martin/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/martin/anaconda3/lib/python3.6/site-packages/verif-1.0.0-py3.6.egg/verif/__init__.py", line 3, in <module>
  File "/home/martin/anaconda3/lib/python3.6/site-packages/verif-1.0.0-py3.6.egg/verif/driver.py", line 6, in <module>
  File "/home/martin/anaconda3/lib/python3.6/site-packages/verif-1.0.0-py3.6.egg/verif/metric.py", line 2, in <module>
ModuleNotFoundError: No module named 'metric_type'

**Comment by martadd** [comment]
Thanks. I will install.
